version: '3'

services:
  whatsapp-scheduler:
    build: .
    container_name: whatsapp-scheduler
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${PGUSER}:${PGPASSWORD}@postgres:5432/${PGDATABASE}
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - USE_SIMULATED_CLIENT=true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - whatsapp-network

  postgres:
    image: postgres:15-alpine
    container_name: whatsapp-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - whatsapp-network
    ports:
      - "5432:5432"

networks:
  whatsapp-network:
    driver: bridge

volumes:
  postgres-data: